// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: student.proto

package packagestu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DisciplineService_SendStudent_FullMethodName = "/discipline.DisciplineService/SendStudent"
)

// DisciplineServiceClient is the client API for DisciplineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisciplineServiceClient interface {
	SendStudent(ctx context.Context, in *StudentInfo, opts ...grpc.CallOption) (*DisciplineResponse, error)
}

type disciplineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDisciplineServiceClient(cc grpc.ClientConnInterface) DisciplineServiceClient {
	return &disciplineServiceClient{cc}
}

func (c *disciplineServiceClient) SendStudent(ctx context.Context, in *StudentInfo, opts ...grpc.CallOption) (*DisciplineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisciplineResponse)
	err := c.cc.Invoke(ctx, DisciplineService_SendStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisciplineServiceServer is the server API for DisciplineService service.
// All implementations must embed UnimplementedDisciplineServiceServer
// for forward compatibility.
type DisciplineServiceServer interface {
	SendStudent(context.Context, *StudentInfo) (*DisciplineResponse, error)
	mustEmbedUnimplementedDisciplineServiceServer()
}

// UnimplementedDisciplineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDisciplineServiceServer struct{}

func (UnimplementedDisciplineServiceServer) SendStudent(context.Context, *StudentInfo) (*DisciplineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendStudent not implemented")
}
func (UnimplementedDisciplineServiceServer) mustEmbedUnimplementedDisciplineServiceServer() {}
func (UnimplementedDisciplineServiceServer) testEmbeddedByValue()                           {}

// UnsafeDisciplineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisciplineServiceServer will
// result in compilation errors.
type UnsafeDisciplineServiceServer interface {
	mustEmbedUnimplementedDisciplineServiceServer()
}

func RegisterDisciplineServiceServer(s grpc.ServiceRegistrar, srv DisciplineServiceServer) {
	// If the following call pancis, it indicates UnimplementedDisciplineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DisciplineService_ServiceDesc, srv)
}

func _DisciplineService_SendStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisciplineServiceServer).SendStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DisciplineService_SendStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisciplineServiceServer).SendStudent(ctx, req.(*StudentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// DisciplineService_ServiceDesc is the grpc.ServiceDesc for DisciplineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DisciplineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discipline.DisciplineService",
	HandlerType: (*DisciplineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendStudent",
			Handler:    _DisciplineService_SendStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student.proto",
}
