apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-agro-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-agro
  template:
    metadata:
      labels:
        app: golang-agro
    spec:
      containers:
      - name: golang-agro
        image: hterraza/goland-server:1.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: golang-agro-srv
  namespace: default
spec:
  selector:
    app: golang-agro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: ClusterIP
