apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-nata-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-nata
  template:
    metadata:
      labels:
        app: golang-nata
    spec:
      containers:
      - name: golang-nata
        image: hterraza/diciplina-server:1.1
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: natacion-svc
  namespace: default
spec:
  selector:
    app: golang-nata
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
