apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-winner-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-winner
  template:
    metadata:
      labels:
        app: golang-winner
    spec:
      containers:
      - name: golang-winner
        image: hterraza/golang-winner:1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"

