apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: golang-box-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-box-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Escalará si el uso de CPU supera el 50%
